const { MongoClient } = require('mongodb');
const fs = require('fs');
const path = require('path');
require('dotenv').config();

async function run() {
  const client = new MongoClient(process.env.MONGODB_URI);
  await client.connect();
  const db = client.db('skool');

  console.log('Connected to MongoDB Atlas: skool database');

  // 1. Ensure Grade 12 Classes Exist
  const grade12Classes = [
    {
      _id: 'cls_12_voc',
      id: 'cls_12_voc',
      name: 'Grade 12',
      section: 'Vocational',
      className: 'Grade 12-Vocational',
      capacity: 35,
      roomNo: 'Room 401',
      description: '12th Standard – Vocational Group',
      academicYear: '2026-2027',
      classTeacher: 'staff_rajesh',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },
    {
      _id: 'cls_12_cs',
      id: 'cls_12_cs',
      name: 'Grade 12',
      section: 'Computer Science',
      className: 'Grade 12-Computer Science',
      capacity: 35,
      roomNo: 'Room 402',
      description: '12th Standard – Computer Science Group',
      academicYear: '2026-2027',
      classTeacher: 'staff_alan',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },
    {
      _id: 'cls_12_sci',
      id: 'cls_12_sci',
      name: 'Grade 12',
      section: 'Science',
      className: 'Grade 12-Science',
      capacity: 35,
      roomNo: 'Room 403',
      description: '12th Standard – Pure Science Group',
      academicYear: '2026-2027',
      classTeacher: 'staff_albert',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },
    {
      _id: 'cls_12_com',
      id: 'cls_12_com',
      name: 'Grade 12',
      section: 'Commerce',
      className: 'Grade 12-Commerce',
      capacity: 35,
      roomNo: 'Room 404',
      description: '12th Standard – Commerce Group',
      academicYear: '2026-2027',
      classTeacher: 'staff_kavitha',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },
    {
      _id: 'cls_12_mb',
      id: 'cls_12_mb',
      name: 'Grade 12',
      section: 'Maths Biology',
      className: 'Grade 12-Maths Biology',
      capacity: 35,
      roomNo: 'Room 405',
      description: '12th Standard – Maths Biology Group',
      academicYear: '2026-2027',
      classTeacher: 'staff_meena',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    }
  ];

  for (const cls of grade12Classes) {
    await db.collection('classes').updateOne({ _id: cls._id }, { $set: cls }, { upsert: true });
  }
  console.log('✅ Grade 12 classes verified & updated in database');

  // Remove existing Grade 12 students to avoid admissionNo index collision
  await db.collection('students').deleteMany({
    $or: [
      { grade: 'Grade 12' },
      { className: /Grade 12/i },
      { class: /cls_12/i },
      { admissionNo: /^STU-12/i }
    ]
  });
  console.log('✅ Cleared existing Grade 12 student records for clean seeding');

  // 2. Comprehensive 25 Grade 12 Students across all 5 groups
  const students = [
    // ─────────────── GROUP 1: VOCATIONAL (5 Students) ───────────────
    {
      _id: 'stu_12_voc_01',
      id: 'stu_12_voc_01',
      admissionNo: 'STU-1201',
      rollNumber: '01',
      name: 'Vimal Raj',
      grade: 'Grade 12',
      section: 'Vocational',
      class: 'cls_12_voc',
      className: 'Grade 12-Vocational',
      academicYear: '2026-2027',
      gender: 'Male',
      dob: '2009-04-12',
      bloodGroup: 'A+',
      email: 'vimal.raj@skool.edu.in',
      phone: '+91 9100000061',
      parentName: 'Rajendran P',
      parentRelation: 'Father',
      parentPhone: '+91 9800000061',
      address: '45, East Car Street, Kovilpatti',
      status: 'Active',
      createdAt: '2026-06-01T09:00:00.000Z',
      updatedAt: new Date().toISOString()
    },
    {
      _id: 'stu_12_voc_02',
      id: 'stu_12_voc_02',
      admissionNo: 'STU-1202',
      rollNumber: '02',
      name: 'Dhanalakshmi S',
      grade: 'Grade 12',
      section: 'Vocational',
      class: 'cls_12_voc',
      className: 'Grade 12-Vocational',
      academicYear: '2026-2027',
      gender: 'Female',
      dob: '2009-08-20',
      bloodGroup: 'B+',
      email: 'dhana.s@skool.edu.in',
      phone: '+91 9100000062',
      parentName: 'Subramanian K',
      parentRelation: 'Father',
      parentPhone: '+91 9800000062',
      address: '18, Market Road, Kovilpatti',
      status: 'Active',
      createdAt: '2026-06-01T09:00:00.000Z',
      updatedAt: new Date().toISOString()
    },
    {
      _id: 'stu_12_voc_03',
      id: 'stu_12_voc_03',
      admissionNo: 'STU-1203',
      rollNumber: '03',
      name: 'Karthik Raja',
      grade: 'Grade 12',
      section: 'Vocational',
      class: 'cls_12_voc',
      className: 'Grade 12-Vocational',
      academicYear: '2026-2027',
      gender: 'Male',
      dob: '2009-01-15',
      bloodGroup: 'O+',
      email: 'karthik.r@skool.edu.in',
      phone: '+91 9100000063',
      parentName: 'Raja Mohan',
      parentRelation: 'Father',
      parentPhone: '+91 9800000063',
      address: '22, Anna Nagar, Kovilpatti',
      status: 'Active',
      createdAt: '2026-06-01T09:00:00.000Z',
      updatedAt: new Date().toISOString()
    },
    {
      _id: 'stu_12_voc_04',
      id: 'stu_12_voc_04',
      admissionNo: 'STU-1204',
      rollNumber: '04',
      name: 'Murugesan K',
      grade: 'Grade 12',
      section: 'Vocational',
      class: 'cls_12_voc',
      className: 'Grade 12-Vocational',
      academicYear: '2026-2027',
      gender: 'Male',
      dob: '2009-03-10',
      bloodGroup: 'AB+',
      email: 'murugesan.k@skool.edu.in',
      phone: '+91 9100000064',
      parentName: 'Karuppasamy M',
      parentRelation: 'Father',
      parentPhone: '+91 9800000064',
      address: '12, Old Bus Stand Road, Kovilpatti',
      status: 'Active',
      createdAt: '2026-06-01T09:00:00.000Z',
      updatedAt: new Date().toISOString()
    },
    {
      _id: 'stu_12_voc_05',
      id: 'stu_12_voc_05',
      admissionNo: 'STU-1205',
      rollNumber: '05',
      name: 'Priyadharshini M',
      grade: 'Grade 12',
      section: 'Vocational',
      class: 'cls_12_voc',
      className: 'Grade 12-Vocational',
      academicYear: '2026-2027',
      gender: 'Female',
      dob: '2009-11-22',
      bloodGroup: 'O-',
      email: 'priyadharshini.m@skool.edu.in',
      phone: '+91 9100000065',
      parentName: 'Muruganandham S',
      parentRelation: 'Father',
      parentPhone: '+91 9800000065',
      address: '7, Mill Colony, Kovilpatti',
      status: 'Active',
      createdAt: '2026-06-01T09:00:00.000Z',
      updatedAt: new Date().toISOString()
    },

    // ─────────────── GROUP 2: COMPUTER SCIENCE (5 Students) ───────────────
    {
      _id: 'stu_12_cs_01',
      id: 'stu_12_cs_01',
      admissionNo: 'STU-1206',
      rollNumber: '01',
      name: 'Ashwin Kumar',
      grade: 'Grade 12',
      section: 'Computer Science',
      class: 'cls_12_cs',
      className: 'Grade 12-Computer Science',
      academicYear: '2026-2027',
      gender: 'Male',
      dob: '2009-05-18',
      bloodGroup: 'O+',
      email: 'ashwin.k@skool.edu.in',
      phone: '+91 9100000066',
      parentName: 'Kumaresan T',
      parentRelation: 'Father',
      parentPhone: '+91 9800000066',
      address: '89, IT Park Road, Kovilpatti',
      status: 'Active',
      createdAt: '2026-06-01T09:00:00.000Z',
      updatedAt: new Date().toISOString()
    },
    {
      _id: 'stu_12_cs_02',
      id: 'stu_12_cs_02',
      admissionNo: 'STU-1207',
      rollNumber: '02',
      name: 'Swetha Ramesh',
      grade: 'Grade 12',
      section: 'Computer Science',
      class: 'cls_12_cs',
      className: 'Grade 12-Computer Science',
      academicYear: '2026-2027',
      gender: 'Female',
      dob: '2009-09-25',
      bloodGroup: 'AB+',
      email: 'swetha.r@skool.edu.in',
      phone: '+91 9100000067',
      parentName: 'Ramesh Sundar',
      parentRelation: 'Father',
      parentPhone: '+91 9800000067',
      address: '14, Gandhi Road, Kovilpatti',
      status: 'Active',
      createdAt: '2026-06-01T09:00:00.000Z',
      updatedAt: new Date().toISOString()
    },
    {
      _id: 'stu_12_cs_03',
      id: 'stu_12_cs_03',
      admissionNo: 'STU-1208',
      rollNumber: '03',
      name: 'Gowtham Balaji',
      grade: 'Grade 12',
      section: 'Computer Science',
      class: 'cls_12_cs',
      className: 'Grade 12-Computer Science',
      academicYear: '2026-2027',
      gender: 'Male',
      dob: '2009-11-04',
      bloodGroup: 'B+',
      email: 'gowtham.b@skool.edu.in',
      phone: '+91 9100000068',
      parentName: 'Balaji V',
      parentRelation: 'Father',
      parentPhone: '+91 9800000068',
      address: '77, Main Bazaar, Kovilpatti',
      status: 'Active',
      createdAt: '2026-06-01T09:00:00.000Z',
      updatedAt: new Date().toISOString()
    },
    {
      _id: 'stu_12_cs_04',
      id: 'stu_12_cs_04',
      admissionNo: 'STU-1209',
      rollNumber: '04',
      name: 'Ananya Sridhar',
      grade: 'Grade 12',
      section: 'Computer Science',
      class: 'cls_12_cs',
      className: 'Grade 12-Computer Science',
      academicYear: '2026-2027',
      gender: 'Female',
      dob: '2009-02-14',
      bloodGroup: 'A+',
      email: 'ananya.s@skool.edu.in',
      phone: '+91 9100000069',
      parentName: 'Sridhar Narayanan',
      parentRelation: 'Father',
      parentPhone: '+91 9800000069',
      address: '31, Shanthi Nagar, Kovilpatti',
      status: 'Active',
      createdAt: '2026-06-01T09:00:00.000Z',
      updatedAt: new Date().toISOString()
    },
    {
      _id: 'stu_12_cs_05',
      id: 'stu_12_cs_05',
      admissionNo: 'STU-1210',
      rollNumber: '05',
      name: 'Vigneshwaran T',
      grade: 'Grade 12',
      section: 'Computer Science',
      class: 'cls_12_cs',
      className: 'Grade 12-Computer Science',
      academicYear: '2026-2027',
      gender: 'Male',
      dob: '2009-07-09',
      bloodGroup: 'O+',
      email: 'vignesh.t@skool.edu.in',
      phone: '+91 9100000070',
      parentName: 'Thirunavukkarasu P',
      parentRelation: 'Father',
      parentPhone: '+91 9800000070',
      address: '53, Bharathi Nagar, Kovilpatti',
      status: 'Active',
      createdAt: '2026-06-01T09:00:00.000Z',
      updatedAt: new Date().toISOString()
    },

    // ─────────────── GROUP 3: SCIENCE (5 Students) ───────────────
    {
      _id: 'stu_12_sci_01',
      id: 'stu_12_sci_01',
      admissionNo: 'STU-1211',
      rollNumber: '01',
      name: 'Naveen Prashanth',
      grade: 'Grade 12',
      section: 'Science',
      class: 'cls_12_sci',
      className: 'Grade 12-Science',
      academicYear: '2026-2027',
      gender: 'Male',
      dob: '2009-03-30',
      bloodGroup: 'A+',
      email: 'naveen.p@skool.edu.in',
      phone: '+91 9100000071',
      parentName: 'Prashanth M',
      parentRelation: 'Father',
      parentPhone: '+91 9800000071',
      address: '33, Science Colony, Kovilpatti',
      status: 'Active',
      createdAt: '2026-06-01T09:00:00.000Z',
      updatedAt: new Date().toISOString()
    },
    {
      _id: 'stu_12_sci_02',
      id: 'stu_12_sci_02',
      admissionNo: 'STU-1212',
      rollNumber: '02',
      name: 'Pavithra Devi',
      grade: 'Grade 12',
      section: 'Science',
      class: 'cls_12_sci',
      className: 'Grade 12-Science',
      academicYear: '2026-2027',
      gender: 'Female',
      dob: '2009-07-14',
      bloodGroup: 'O-',
      email: 'pavithra.d@skool.edu.in',
      phone: '+91 9100000072',
      parentName: 'Dhanushkodi R',
      parentRelation: 'Father',
      parentPhone: '+91 9800000072',
      address: '5, Teachers Colony, Kovilpatti',
      status: 'Active',
      createdAt: '2026-06-01T09:00:00.000Z',
      updatedAt: new Date().toISOString()
    },
    {
      _id: 'stu_12_sci_03',
      id: 'stu_12_sci_03',
      admissionNo: 'STU-1213',
      rollNumber: '03',
      name: 'Saravanan B',
      grade: 'Grade 12',
      section: 'Science',
      class: 'cls_12_sci',
      className: 'Grade 12-Science',
      academicYear: '2026-2027',
      gender: 'Male',
      dob: '2009-06-19',
      bloodGroup: 'B+',
      email: 'saravanan.b@skool.edu.in',
      phone: '+91 9100000073',
      parentName: 'Balasubramanian S',
      parentRelation: 'Father',
      parentPhone: '+91 9800000073',
      address: '19, Railway Feeder Road, Kovilpatti',
      status: 'Active',
      createdAt: '2026-06-01T09:00:00.000Z',
      updatedAt: new Date().toISOString()
    },
    {
      _id: 'stu_12_sci_04',
      id: 'stu_12_sci_04',
      admissionNo: 'STU-1214',
      rollNumber: '04',
      name: 'Deepa Lakshmi',
      grade: 'Grade 12',
      section: 'Science',
      class: 'cls_12_sci',
      className: 'Grade 12-Science',
      academicYear: '2026-2027',
      gender: 'Female',
      dob: '2009-10-05',
      bloodGroup: 'A1B+',
      email: 'deepa.l@skool.edu.in',
      phone: '+91 9100000074',
      parentName: 'Lakshmanan K',
      parentRelation: 'Father',
      parentPhone: '+91 9800000074',
      address: '42, State Bank Colony, Kovilpatti',
      status: 'Active',
      createdAt: '2026-06-01T09:00:00.000Z',
      updatedAt: new Date().toISOString()
    },
    {
      _id: 'stu_12_sci_05',
      id: 'stu_12_sci_05',
      admissionNo: 'STU-1215',
      rollNumber: '05',
      name: 'Kishore Kumar',
      grade: 'Grade 12',
      section: 'Science',
      class: 'cls_12_sci',
      className: 'Grade 12-Science',
      academicYear: '2026-2027',
      gender: 'Male',
      dob: '2009-12-18',
      bloodGroup: 'B-',
      email: 'kishore.k@skool.edu.in',
      phone: '+91 9100000075',
      parentName: 'Kumarasamy A',
      parentRelation: 'Father',
      parentPhone: '+91 9800000075',
      address: '8, North Street, Kovilpatti',
      status: 'Active',
      createdAt: '2026-06-01T09:00:00.000Z',
      updatedAt: new Date().toISOString()
    },

    // ─────────────── GROUP 4: COMMERCE (5 Students) ───────────────
    {
      _id: 'stu_12_com_01',
      id: 'stu_12_com_01',
      admissionNo: 'STU-1216',
      rollNumber: '01',
      name: 'Harish Raghav',
      grade: 'Grade 12',
      section: 'Commerce',
      class: 'cls_12_com',
      className: 'Grade 12-Commerce',
      academicYear: '2026-2027',
      gender: 'Male',
      dob: '2009-02-19',
      bloodGroup: 'B-',
      email: 'harish.r@skool.edu.in',
      phone: '+91 9100000076',
      parentName: 'Raghavan S',
      parentRelation: 'Father',
      parentPhone: '+91 9800000076',
      address: '11, Bank Street, Kovilpatti',
      status: 'Active',
      createdAt: '2026-06-01T09:00:00.000Z',
      updatedAt: new Date().toISOString()
    },
    {
      _id: 'stu_12_com_02',
      id: 'stu_12_com_02',
      admissionNo: 'STU-1217',
      rollNumber: '02',
      name: 'Keerthana Anand',
      grade: 'Grade 12',
      section: 'Commerce',
      class: 'cls_12_com',
      className: 'Grade 12-Commerce',
      academicYear: '2026-2027',
      gender: 'Female',
      dob: '2009-06-08',
      bloodGroup: 'A1B+',
      email: 'keerthana.a@skool.edu.in',
      phone: '+91 9100000077',
      parentName: 'Anand Kumar',
      parentRelation: 'Father',
      parentPhone: '+91 9800000077',
      address: '28, Trade Center, Kovilpatti',
      status: 'Active',
      createdAt: '2026-06-01T09:00:00.000Z',
      updatedAt: new Date().toISOString()
    },
    {
      _id: 'stu_12_com_03',
      id: 'stu_12_com_03',
      admissionNo: 'STU-1218',
      rollNumber: '03',
      name: 'Manikandan P',
      grade: 'Grade 12',
      section: 'Commerce',
      class: 'cls_12_com',
      className: 'Grade 12-Commerce',
      academicYear: '2026-2027',
      gender: 'Male',
      dob: '2009-04-25',
      bloodGroup: 'O+',
      email: 'mani.p@skool.edu.in',
      phone: '+91 9100000078',
      parentName: 'Perumal S',
      parentRelation: 'Father',
      parentPhone: '+91 9800000078',
      address: '61, Kamaraj Nagar, Kovilpatti',
      status: 'Active',
      createdAt: '2026-06-01T09:00:00.000Z',
      updatedAt: new Date().toISOString()
    },
    {
      _id: 'stu_12_com_04',
      id: 'stu_12_com_04',
      admissionNo: 'STU-1219',
      rollNumber: '04',
      name: 'Sandhya Venkatesh',
      grade: 'Grade 12',
      section: 'Commerce',
      class: 'cls_12_com',
      className: 'Grade 12-Commerce',
      academicYear: '2026-2027',
      gender: 'Female',
      dob: '2009-08-31',
      bloodGroup: 'B+',
      email: 'sandhya.v@skool.edu.in',
      phone: '+91 9100000079',
      parentName: 'Venkatesh Babu',
      parentRelation: 'Father',
      parentPhone: '+91 9800000079',
      address: '39, Gandhi Nagar, Kovilpatti',
      status: 'Active',
      createdAt: '2026-06-01T09:00:00.000Z',
      updatedAt: new Date().toISOString()
    },
    {
      _id: 'stu_12_com_05',
      id: 'stu_12_com_05',
      admissionNo: 'STU-1220',
      rollNumber: '05',
      name: 'Sanjay Kannan',
      grade: 'Grade 12',
      section: 'Commerce',
      class: 'cls_12_com',
      className: 'Grade 12-Commerce',
      academicYear: '2026-2027',
      gender: 'Male',
      dob: '2009-12-01',
      bloodGroup: 'A+',
      email: 'sanjay.k@skool.edu.in',
      phone: '+91 9100000080',
      parentName: 'Kannan K',
      parentRelation: 'Father',
      parentPhone: '+91 9800000080',
      address: '15, Post Office Street, Kovilpatti',
      status: 'Active',
      createdAt: '2026-06-01T09:00:00.000Z',
      updatedAt: new Date().toISOString()
    },

    // ─────────────── GROUP 5: MATHS BIOLOGY (5 Students) ───────────────
    {
      _id: 'stu_12_mb_01',
      id: 'stu_12_mb_01',
      admissionNo: 'STU-1221',
      rollNumber: '01',
      name: 'Sudharsan S',
      grade: 'Grade 12',
      section: 'Maths Biology',
      class: 'cls_12_mb',
      className: 'Grade 12-Maths Biology',
      academicYear: '2026-2027',
      gender: 'Male',
      dob: '2009-01-28',
      bloodGroup: 'O+',
      email: 'sudharsan.s@skool.edu.in',
      phone: '+91 9100000081',
      parentName: 'Senthur Pandian',
      parentRelation: 'Father',
      parentPhone: '+91 9800000081',
      address: '10, Doctors Lane, Kovilpatti',
      status: 'Active',
      createdAt: '2026-06-01T09:00:00.000Z',
      updatedAt: new Date().toISOString()
    },
    {
      _id: 'stu_12_mb_02',
      id: 'stu_12_mb_02',
      admissionNo: 'STU-1222',
      rollNumber: '02',
      name: 'Abinaya Murugan',
      grade: 'Grade 12',
      section: 'Maths Biology',
      class: 'cls_12_mb',
      className: 'Grade 12-Maths Biology',
      academicYear: '2026-2027',
      gender: 'Female',
      dob: '2009-10-11',
      bloodGroup: 'B+',
      email: 'abinaya.m@skool.edu.in',
      phone: '+91 9100000082',
      parentName: 'Murugan P',
      parentRelation: 'Father',
      parentPhone: '+91 9800000082',
      address: '64, Green Garden, Kovilpatti',
      status: 'Active',
      createdAt: '2026-06-01T09:00:00.000Z',
      updatedAt: new Date().toISOString()
    },
    {
      _id: 'stu_12_mb_03',
      id: 'stu_12_mb_03',
      admissionNo: 'STU-1223',
      rollNumber: '03',
      name: 'Vijay Sethupathi',
      grade: 'Grade 12',
      section: 'Maths Biology',
      class: 'cls_12_mb',
      className: 'Grade 12-Maths Biology',
      academicYear: '2026-2027',
      gender: 'Male',
      dob: '2009-05-02',
      bloodGroup: 'AB+',
      email: 'vijay.s@skool.edu.in',
      phone: '+91 9100000083',
      parentName: 'Sethupathi R',
      parentRelation: 'Father',
      parentPhone: '+91 9800000083',
      address: '27, Medical Colony, Kovilpatti',
      status: 'Active',
      createdAt: '2026-06-01T09:00:00.000Z',
      updatedAt: new Date().toISOString()
    },
    {
      _id: 'stu_12_mb_04',
      id: 'stu_12_mb_04',
      admissionNo: 'STU-1224',
      rollNumber: '04',
      name: 'Soundarya R',
      grade: 'Grade 12',
      section: 'Maths Biology',
      class: 'cls_12_mb',
      className: 'Grade 12-Maths Biology',
      academicYear: '2026-2027',
      gender: 'Female',
      dob: '2009-09-17',
      bloodGroup: 'A+',
      email: 'soundarya.r@skool.edu.in',
      phone: '+91 9100000084',
      parentName: 'Ramamoorthy N',
      parentRelation: 'Father',
      parentPhone: '+91 9800000084',
      address: '14, Lakshmi Nagar, Kovilpatti',
      status: 'Active',
      createdAt: '2026-06-01T09:00:00.000Z',
      updatedAt: new Date().toISOString()
    },
    {
      _id: 'stu_12_mb_05',
      id: 'stu_12_mb_05',
      admissionNo: 'STU-1225',
      rollNumber: '05',
      name: 'Gokul Nathan',
      grade: 'Grade 12',
      section: 'Maths Biology',
      class: 'cls_12_mb',
      className: 'Grade 12-Maths Biology',
      academicYear: '2026-2027',
      gender: 'Male',
      dob: '2009-12-29',
      bloodGroup: 'O+',
      email: 'gokul.n@skool.edu.in',
      phone: '+91 9100000085',
      parentName: 'Natarajan S',
      parentRelation: 'Father',
      parentPhone: '+91 9800000085',
      address: '52, Hospital Road, Kovilpatti',
      status: 'Active',
      createdAt: '2026-06-01T09:00:00.000Z',
      updatedAt: new Date().toISOString()
    }
  ];

  // Insert or update all students
  let inserted = 0;
  for (const stu of students) {
    await db.collection('students').updateOne(
      { _id: stu._id },
      { $set: stu },
      { upsert: true }
    );
    inserted++;
  }
  console.log(`✅ Successfully stored ${inserted} Grade 12 student records into MongoDB Atlas`);

  // Verify counts in DB
  const total12 = await db.collection('students').countDocuments({
    $or: [{ grade: 'Grade 12' }, { className: /Grade 12/i }]
  });
  const totalAll = await db.collection('students').countDocuments();
  console.log(`📊 Grade 12 students in database: ${total12}`);
  console.log(`📊 Total students across all classes in database: ${totalAll}`);

  // Also export full updated database into liveDbData.js
  const collections = [
    'users', 'students', 'staffs', 'classes', 'subjects', 'attendances',
    'fees', 'exams', 'grades', 'timetables', 'events', 'notices',
    'leaves', 'library', 'transport', 'hostel', 'settings', 'admissions'
  ];

  const fullData = {};
  for (const col of collections) {
    fullData[col] = await db.collection(col).find({}).toArray();
  }

  const fileContent = `export const liveDbData = ${JSON.stringify(fullData, null, 2)};\n`;
  const destPath = path.join(__dirname, '..', 'src', 'data', 'liveDbData.js');
  fs.writeFileSync(destPath, fileContent, 'utf8');
  console.log(`✅ Successfully synchronized ${destPath} with latest MongoDB Atlas records`);

  await client.close();
}

run().catch(console.error);
